menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'blog', url: '/blog'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


courses:
- {name: 'Forthcoming'}

social:
- {icon: 'github', link: 'https://github.com/graziasveva'}
- {icon: 'twitter', link: 'https://twitter.com/grazia_sveva'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/graziasvevaascione'}
- {icon: 'orcid', link: 'https://orcid.org/my-orcid?orcid=0000-0002-9719-5291'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=OK-lmGgAAAAJ&hl=it&oi=ao'}



contacts:
- {name: 'Dr. Grazia Sveva Ascione', title: 'Postdoc', department: 'Economics', institution: 'University of Bordeaux', institution_address: '6 Av. Léon Duguit, 33600 Pessac', email: 'graziasveva@gmail.com', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
